version: 0.2

phases:
  install:
    commands:
      # install NodeJS 12
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs

      # install yarn
      - echo Installing Yarn...
      - curl sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "dev https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt install --no-install-recommends yarn
  pre_build:
    commands:
      # install dependencies
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      # run tests
      # - echo Testing...
      # - yarn test

      # build
      - echo Building...
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist